# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook 
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

# MAGIC %sql
# MAGIC -- !!! Before performing any data analysis, make sure to run the pipeline to materialize the sample datasets. The tables referenced in this notebook depend on that step.
# MAGIC
# MAGIC USE CATALOG `mgiglia`;
# MAGIC USE SCHEMA `synthea`;
# MAGIC
# MAGIC SELECT * from sample_trips_may_8_329;

# COMMAND ----------

import os
import json
data_sources_dir = "../data_sources"
json_files = [f for f in os.listdir(data_sources_dir) if f.endswith('.json')]

data_array = []
for json_file in json_files:
    with open(os.path.join(data_sources_dir, json_file), 'r') as file:
        data_array.append(json.load(file))

# COMMAND ----------

data_array
